server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html index.htm;

    location ~* (runtime|application)/ {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.php?s=$uri&$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PHP_VALUE "upload_max_filesize = 100M \n post_max_size = 100M";
    }

    location ~ /\.ht {
        deny all;
    }
}
